services:
  web:
    build: .
    container_name: php
    ports:
      - "8080:80"
    volumes:
      - ./src/html:/var/www/html
      - ./config:/usr/local/etc/php
    depends_on:
     - db
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    environment:
      PMA_JOST: db
      PMA_USER: so-take
      PMA_PASSWORD: Lg155Tenkyu
    depends_on:
      - db
    ports:
      - "8081:80"
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Lg155Zikishin
      MYSQL_DATABASE: testdb
      MYSQL_USER: so-take
      MYSQL_PASSWORD: Lg155Tenkyu
#    ports:
#      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: